language: php
dist: precise
matrix:
  include:
    - php: 7.1

php:
  - 7.1
  - 7.2

sudo: false

script:
  - vendor/bin/phpcs --standard=psr2 --extensions=php --warning-severity=0 --report=full "src"
  - travis_wait 20 vendor/bin/simple-phpunit --coverage-clover=coverage.clover

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_failure:
  - cat var/logs/test.log

matrix:
  fast_finish: true
